# Generated by Django 3.1 on 2020-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('stud_num', models.IntegerField(blank=True, db_column='Stud_num', null=True)),
                ('batch_no', models.CharField(db_column='Batch_no', max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.IntegerField(db_column='Mentor_id', primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(blank=True, db_column='Mentor_name', max_length=25, null=True)),
            ],
            options={
                'db_table': 'mentor',
                'managed': False,
            },
        ),
    ]
