# Generated by Django 3.1 on 2020-12-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_no', models.IntegerField(db_column='Class_No', primary_key=True, serialize=False)),
                ('class_date', models.DateField(blank=True, db_column='Class_Date', null=True)),
                ('start_time', models.TimeField(blank=True, db_column='Start_Time', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='End_time', null=True)),
                ('imp_notice', models.CharField(blank=True, db_column='Imp_notice', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planned',
            fields=[
                ('batch_no', models.OneToOneField(db_column='Batch_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='student.batch')),
            ],
            options={
                'db_table': 'planned',
                'managed': False,
            },
        ),
    ]
